### ISSUE TITLE
This interferes with SoundPhysics somehow, 1.16.5-forge-36.1.4 

### ISSUE THREAD

**Issue by Eleshz** [iChun/BackTools#17]
It gets to the forge loading bar and then it says freezing data, THEN it crashes and gives exit code: 0

**Comment by iChun** [comment]
A crash log would be nice.

**Comment by Eleshz** [comment]
Ok, Sorry for lots of text.... :(
 ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/29/21 3:37 PM
Description: Rendering overlay

java.lang.NoClassDefFoundError: com/sonicether/soundphysics/SoundPhysics
	at net.minecraft.client.audio.SoundSystem.func_216404_a(SourceFile:147) ~[?:?] {re:classloading,xf:soundphysics_transformer:default}
	at net.minecraft.client.audio.SoundEngine.func_148608_i(SoundEngine.java:81) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:soundphysics_transformer:default,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundEngine.func_148596_a(SoundEngine.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:soundphysics_transformer:default,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundHandler.func_212853_a_(SoundHandler.java:109) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundHandler.func_212853_a_(SoundHandler.java:34) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3449/272530556.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3634/476238509.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3435/486965279.execute(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.texture.TextureManager$$Lambda$3637/1705294294.execute(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$449/1652393238.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.audio.SoundSystem.func_216404_a(SourceFile:147) ~[?:?] {re:classloading,xf:soundphysics_transformer:default}
	at net.minecraft.client.audio.SoundEngine.func_148608_i(SoundEngine.java:81) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:soundphysics_transformer:default,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundEngine.func_148596_a(SoundEngine.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:soundphysics_transformer:default,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundHandler.func_212853_a_(SoundHandler.java:109) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.audio.SoundHandler.func_212853_a_(SoundHandler.java:34) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3449/272530556.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3634/476238509.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:111) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3435/486965279.execute(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.texture.TextureManager$$Lambda$3637/1705294294.execute(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$449/1652393238.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3172883336 bytes (3025 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.5_HD_U_G8_pre11.jar OptiFine TRANSFORMATIONSERVICE 
		/Sound-Physics-1.16.3-1.0.10-1.jar soundphysics_transformer TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.5-0.5.5.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |NONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Launched Version: 1.16.5-forge-36.1.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre11
	OptiFine Build: 20210324-231709
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by iChun** [comment]
Are you sure Back Tools affects this? You got a bunch of core mods as well
and back tools doesn't even touch sounds. I also don't see what mods are
installed from your crash log so I can't confirm that back tools is
installed. You might have to try and rebuild your Minecraft environment.

**Comment by Eleshz** [comment]
Sorry about all the other mods, they all work fine and then when I add BackTools it crashes and says something went wrong with soundphysics. Remove BackTools and it's fine.

**Comment by iChun** [comment]
I'll have to look into this, I don't know when that'll be though. Really
not sure why this is happening.
